import { randomUUID } from "node:crypto";
import { hashBlake3 } from "@midim/shared";
import type {
  PoimCertificate,
  PoimCertificateMetadata,
  PoimVerifyResult,
} from "@midim/shared";
import { signCertPayload, verifyCertSignature } from "./crypto.js";

export const POIM_DISCLAIMER =
  "This is a LOCAL SELF-SIGNED certificate generated by MIDIM OSS tools. " +
  "It has NOT been submitted to or verified by any POIM registry. " +
  "It confers no marketplace eligibility, rights confidence score, or registry-backed provenance. " +
  "For registry-backed POIM, corpus similarity search, rights registry lookup, " +
  "and marketplace eligibility, visit MIDIM.net.";

export function signCertificate(
  buffer: Uint8Array,
  privkeyHex: string,
  pubkeyHex: string,
  metadata: PoimCertificateMetadata = {}
): PoimCertificate {
  const assetHash = hashBlake3(buffer);
  const certId = randomUUID();
  const issuedAt = new Date().toISOString();

  const rightsStatement = metadata.rights_statement ?? {
    statement:
      "Self-certified: creator asserts original authorship or rights to this MIDI file.",
    license: null,
  };

  const unsignedPayload: Record<string, unknown> = {
    poim_version: "1.0",
    certificate_type: "local_self_signed",
    cert_id: certId,
    asset_type: "midi",
    asset_hash_alg: "BLAKE3",
    asset_hash: assetHash,
    asset_filename: metadata.filename ?? null,
    creator_pubkey_ed25519: metadata.creator_pubkey_ed25519 ?? null,
    issuer_pubkey_ed25519: pubkeyHex,
    source_work: metadata.source_work ?? null,
    rights_statement: rightsStatement,
    issued_at: issuedAt,
    signature_alg: "Ed25519",
    disclaimer: POIM_DISCLAIMER,
  };

  const signature = signCertPayload(unsignedPayload, privkeyHex);

  return {
    ...(unsignedPayload as Omit<PoimCertificate, "signature">),
    signature,
  } as PoimCertificate;
}

export function verifyCertificate(
  buffer: Uint8Array,
  certificate: PoimCertificate
): PoimVerifyResult {
  const expectedHash = hashBlake3(buffer);
  const assetHashMatch = certificate.asset_hash === expectedHash;

  if (!assetHashMatch) {
    return {
      valid: false,
      asset_hash_verified: false,
      signature_verified: false,
      error: `Asset hash mismatch — the MIDI file has changed since certification. Expected: ${certificate.asset_hash.slice(0, 16)}… Got: ${expectedHash.slice(0, 16)}…`,
    };
  }

  const sigResult = verifyCertSignature(
    certificate as unknown as Record<string, unknown>
  );

  return {
    valid: sigResult.valid,
    asset_hash_verified: true,
    signature_verified: sigResult.valid,
    ...(sigResult.error !== undefined ? { error: sigResult.error } : {}),
  };
}
